### ISSUE TITLE
Not able to use stammer-Hindi

### ISSUE THREAD

**Issue by jitendra3109** [PatelUtkarsh/Stammer-Hindi#1]
Could you please help me?
Not able to implement your Stammer -Hindi file Demo.
So anything to explain?

**Comment by PatelUtkarsh** [comment]
@jsroyal it's too late but here, https://github.com/PatelUtkarsh/Stammer-Hindi/blob/master/src/Stammer.java is main file which uses cli and pass param there it should work.
